# Generated by Django 5.0 on 2023-12-04 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=10)),
                ('lesson_1', models.CharField(max_length=50)),
                ('lesson_2', models.CharField(max_length=50)),
                ('lesson_3', models.CharField(max_length=50)),
                ('lesson_4', models.CharField(max_length=50)),
                ('lesson_5', models.CharField(max_length=50)),
                ('lesson_6', models.CharField(max_length=50)),
                ('lesson_7', models.CharField(max_length=50)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.class')),
            ],
        ),
    ]
