# Generated by Django 5.1.3 on 2025-02-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0002_alter_article_user_alter_subject_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="class_name",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="plan",
        ),
        migrations.AddField(
            model_name="subjectplancreator",
            name="class_name",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainpage.class",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subjectplancreator",
            name="plan",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="PupilClass",
        ),
    ]
