# Generated by Django 5.0 on 2023-12-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('lesson_date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
