# Generated by Django 5.1.3 on 2025-02-22 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0003_remove_subject_class_name_remove_subject_plan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectplancreator",
            name="creator",
            field=models.ForeignKey(
                limit_choices_to={
                    "role__in": ["teacher", "deputy director", "director"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="classteacher",
            constraint=models.UniqueConstraint(
                fields=("class_name", "subject"), name="unique_class_subject"
            ),
        ),
    ]
