# Generated by Django 5.0 on 2023-12-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='grade',
            field=models.PositiveSmallIntegerField(default=None, max_length=1, null=True),
        ),
    ]
