# Generated by Django 5.1.3 on 2025-02-22 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0004_alter_subjectplancreator_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subjectplancreator",
            constraint=models.UniqueConstraint(
                fields=("class_name", "subject"), name="unique_plan_subject"
            ),
        ),
    ]
