# Generated by Django 5.0 on 2023-12-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_journal_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='grade',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='lesson_date',
            field=models.CharField(max_length=12),
        ),
    ]
