# Generated by Django 5.1.3 on 2025-02-23 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0005_subjectplancreator_unique_plan_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mark",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name="Quarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 четверть"),
                            (2, "2 четверть"),
                            (3, "3 четверть"),
                            (4, "4 четверть"),
                        ]
                    ),
                ),
                ("begin", models.DateField()),
                ("end", models.DateField()),
                ("year", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["year", "name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("begin__lt", models.F("end"))),
                        name="begin_before_end",
                    )
                ],
            },
        ),
    ]
