# Generated by Django 5.1.3 on 2025-03-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0007_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="class_teacher",
        ),
        migrations.AddField(
            model_name="schedule",
            name="class_field",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainpage.class",
            ),
            preserve_default=False,
        ),
    ]
