# Generated by Django 5.1.3 on 2025-03-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0008_remove_schedule_class_teacher_schedule_class_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="lesson_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_1",
                to="mainpage.subject",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_2",
                to="mainpage.subject",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_3",
                to="mainpage.subject",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_4",
                to="mainpage.subject",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_5",
                to="mainpage.subject",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_6",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_6",
                to="mainpage.subject",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_7",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_7",
                to="mainpage.subject",
            ),
        ),
    ]
