# Generated by Django 5.1.3 on 2025-03-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0009_alter_schedule_lesson_1_alter_schedule_lesson_2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.ImageField(upload_to="articles/")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainpage.article",
                    ),
                ),
            ],
        ),
    ]
