# Generated by Django 5.1.3 on 2025-03-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0010_articleimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="url",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
        migrations.DeleteModel(
            name="ArticleImage",
        ),
    ]
