# Generated by Django 5.0 on 2023-12-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_rename_lessondate_lesson'),
        ('mainpage', '0016_dates_delete_lesson'),
    ]

    operations = [
    ]
