# Generated by Django 5.0 on 2023-12-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_merge_20231213_0333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dates',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
