# Generated by Django 5.0 on 2023-12-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_alter_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='old_date',
            field=models.CharField(default='x', max_length=10),
        ),
    ]
